apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginex-appset
spec:
  generators:
    - git:
        files:
          - path: services/settings.yaml
        repoURL: https://github.com/The-Cloud-Panda/argocd-appset.git
        revision: HEAD
  template:
    metadata:
      namespace: nginex
    spec:
      project: argocd
      source:
        repoURL: https://github.com/helm/charts.git # URL of your NGINX Git repository
        path: "{{ argocd.chart.path }}" # Path to the directory containing NGINX manifests
        targetRevision: master # Replace with the desired branch or tag
        helm:
          ignoreMissingValueFiles: true
          parameters:
            - name: nameOverride
              value: "{{ path[1] }}"
          valueFiles:
            # chart values, default plus override for 3rd parties
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: nginex # Namespace where NGINX will be deployed
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
