apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: services/*/krabs-qa/settings.yaml
        repoURL: https://github.com/The-Cloud-Panda/argocd-appset.git
        revision: HEAD
  template:
    metadata:
      name: "{{ path[1] }}-{{ path.basename }}"
      namespace: argocd
    spec:
      project: argocd
      source:
        repoURL: https://github.com/nginxinc/helm-charts.git # URL of your NGINX Git repository
        path: / # Path to the directory containing NGINX manifests
        targetRevision: master # Replace with the desired branch or tag
      destination:
        server: "product-devops-eks"
        namespace: nginx-namespace # Namespace where NGINX will be deployed
    syncPolicy:
      automated:
        allowEmpty: true
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
